dist: trusty

language: python

python:
  - 2.7

cache: pip

branches:
  only:
    - master
    - develop

notifications:
  email:
    on_success: change
    on_failure: change

before_install:
  - pip install --upgrade --quiet pip setuptools wheel

install:
  # Install test and package dependencies
  - pip install --upgrade --quiet flake8
  - pip install --upgrade --quiet --requirement requirements.txt

script:
  - flake8 lux.py
